src/routes/about.py
from flask import Blueprint, render_template,session, redirect, url_for
from src.database import get_user_by_id

about_bp = Blueprint('about',__name__)

@about_bp.route('/', methods=['GET'])
def Home():
    user = session.get('user')  # Get user data from session if it exists, otherwise None

    if user:
        user_id = user['_id']
        user_data = get_user_by_id(user_id)

        if user_data is None:
            return "User not found", 404

        display_data = {'profile_pic': user_data.get('profile_pic')}
    else:
        # Use default data if user is not in session
        display_data = {'profile_pic': 'default_profile_pic.jpg'}  # Replace with a path to a default image if desired

    return render_template('index.html', display_data=display_data)


@about_bp.route('/about')
def about():
    return render_template('about.html')

src/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from src.profile.form import SignupForm, LoginForm
from src.database import create_user, find_user
from passlib.hash import argon2
from argon2 import PasswordHasher
import pyotp
from src.profile.verification_email import send
import datetime
from argon2.exceptions import VerifyMismatchError
auth_bp = Blueprint('auth', __name__)

argon2 = PasswordHasher()
otp_secrets = {}





@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        if find_user({'username': form.username.data}) and find_user({'email': form.email.data}):
            flash('User already exists', 'error')
        else:
            otp_secret = pyotp.random_base32()  # Generate secret key
            totp = pyotp.TOTP(otp_secret)
            otp = totp.now()  # Generate OTP based on the secret key
            send(form.email.data, otp)  # Send OTP via email

            otp_secrets[form.email.data] = {
                'otp_secret': otp_secret,
                'user_data': {
                    'name': form.name.data,
                    'username': form.username.data,
                    'email': form.email.data,
                    'gender' : form.gender.data,
                    'dob' : form.dob.data,
                    'password': argon2.hash(form.password.data)
                }
            }
            return redirect(url_for('auth.verify_otp', email=form.email.data))
    return render_template('signup.html', form=form)



@auth_bp.route('/verify_otp/<email>', methods=['GET', 'POST'])
def verify_otp(email):
    otp_data = otp_secrets.get(email)
    

    if request.method == 'POST' and otp_data: 
        # Using default interval (30 seconds) and increase valid window to 10 for 5 minutes
        totp = pyotp.TOTP(otp_data['otp_secret'])
        
        if totp.verify(request.form['otp'], valid_window=10):  # Verify OTP with a 5-minute window
            create_user(otp_data['user_data'])
            otp_secrets.pop(email, None)  # Clean up after successful signup
            flash('OTP verified! Signup complete.', 'success')
            return redirect(url_for('auth.login'))
        flash('Invalid or expired OTP.', 'error')
    
    return render_template('verify_otp.html')




@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if user := session.get('user'):
        return redirect(url_for('profile.profile'))
    if form.validate_on_submit():
        login_input = form.username.data or form.email.data
        password = form.password.data

        user = find_user(login_input)
        
        if not user:
            flash('Username or email not found', 'error')
            return render_template('login.html', form=form)
        
        try:
            if argon2.verify(user['password'], password):
                user['_id'] = str(user['_id'])  # Convert ObjectId to string for session storage
                session['user'] = user
                return redirect(url_for('about.Home'))
            else:
                flash('Invalid password', 'error')
        except VerifyMismatchError:
            flash('Invalid password', 'error')

    return render_template('login.html', form=form)


@auth_bp.route('/logout')
def logout():
    session.pop('user', None)
    return redirect(url_for('about.Home'))

src/routes/medical_bot.py
from src.database import get_user_by_id
from flask import Blueprint, render_template, request,redirect, url_for, session
from src.Chatbot.helper import download_hugging_face_embeddings
from langchain_pinecone import PineconeVectorStore
from langchain.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.chains import RetrievalQA
from dotenv import load_dotenv
from src.Chatbot.prompt import *
from langchain_community.vectorstores import Pinecone
import os
bot_bp = Blueprint('medical', __name__)

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")
PINECONE_API_ENV = os.getenv("PINECONE_API_ENV")
from pinecone.grpc import PineconeGRPC as Pinecone

pc = Pinecone(api_key=PINECONE_API_KEY)

embeddings = download_hugging_face_embeddings()

index_name = "medical-bot"

index = pc.Index(index_name)
docsearch = PineconeVectorStore(index=index, embedding=embeddings)

PROMPT = PromptTemplate(template=prompt_template, input_variables=["context", "question"])

chain_type_kwargs = {"prompt": PROMPT}

llm = ChatGoogleGenerativeAI(model="models/gemini-1.5-flash", temperature=0.8, google_api_key=GOOGLE_API_KEY)

qa = RetrievalQA.from_chain_type(
    llm=llm, 
    chain_type="stuff", 
    retriever=docsearch.as_retriever(search_kwargs={'k': 2}),
    return_source_documents=True, 
    chain_type_kwargs=chain_type_kwargs
)


@bot_bp.route("/chat")
def index():
    user = session.get('user')
    if user:
        user_id = user['_id']
        user_data = get_user_by_id(user_id)

        if user_data is None:
            return "User not found", 404

        display_data = {'profile_pic': user_data.get('profile_pic')}
    else:
        # Use default data if user is not in session
        display_data = {'profile_pic': 'default_profile_pic.jpg'}

    return render_template('chat.html', display_data=display_data)  # Pass user data to the template

@bot_bp.route("/get", methods=["GET", "POST"])
def chat():
    msg = request.form["msg"]
    input = msg
    result = qa.invoke({"query": input})
    return str(result["result"])

src/routes/new_summ.py
from flask import Blueprint, render_template, request, redirect, url_for,session
from flask import jsonify
from src.News_Summarizer.process import summarizeTextP,scrape_article
from src.database import get_user_by_id
from src.News_Summarizer.model_load import prediction_model
text_summarzize = Blueprint('text', __name__)

@text_summarzize.route('/news_summarize', methods=['GET'])
def index():
    
    user = session.get('user')  # Get user data from session if it exists, otherwise None

    if user:
        user_id = user['_id']
        user_data = get_user_by_id(user_id)

        if user_data is None:
            return "User not found", 404

        display_data = {'profile_pic': user_data.get('profile_pic')}
    else:
        # Use default data if user is not in session
        display_data = {'profile_pic': 'default_profile_pic.jpg'}
    return render_template("summarize.html", display_data=display_data)

@text_summarzize.route('/summarize', methods=['POST'])
def summarize():
    data = request.get_json()

    # Check for both options
    url = data.get("url", "")
    text = data.get("text", "")

    if not url and not text:
        return jsonify({"error": "No URL or text provided"}), 400

    # If URL is provided, scrape the article
    if url:
        article_text = scrape_article(url)
        if not article_text:
            return jsonify({"error": "Failed to scrape article"}), 500
        input_text = article_text
    else:
        # Use the raw text provided
        input_text = text
    print(input_text)
    # Summarize the input text
    summary = summarizeTextP(input_text, prediction_model) 
    print(summary) # Replace `None` with your actual model
    return jsonify({"summary": summary})

src/routes/news.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
import requests
from src.Intelli_News.intelli_news_function import search_bing_news

news_bp = Blueprint('news', __name__)

@news_bp.route('/Intelli_news', methods=['GET'])
def index():
    # Check if a search query is provided in the URL
    query = request.args.get('query')
    try:
        if query:
            # Perform a search if a query parameter exists
            results = search_bing_news(query)
        else:
            # Use a general query to fetch the latest news
            results = search_bing_news("latest news")
    except requests.RequestException:
        # Handle internet connection issues
        return "Lost Internet Connection", 503  # 503 status for service unavailable

    return render_template('news.html', results=results)

@news_bp.route('/category/<category>')
def news_category(category):
    # Fetch news by category
    results = search_bing_news(category)
    return render_template('news.html', results=results)

src/routes/notes.py
from flask import render_template, request, send_file, redirect, url_for, flash, jsonify, Blueprint, session
from datetime import datetime, timedelta
import os
import uuid
import secrets
from src.database import notes_collection
from bson.objectid import ObjectId
from io import BytesIO

notes = Blueprint('notes_app', __name__)

UPLOAD_FOLDER = 'downloads'

# Ensure the downloads folder exists
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

@notes.route('/all_notes', methods=['GET'])
def all_notes():
    user_id = session.get('user', {}).get('_id')
    if not user_id:
        flash('Please login to view your notes.', 'info')
        return redirect(url_for('auth.login'))
    
    # Fetch only the notes for the specific user
    notes_list = list(notes_collection.find({"user_id": ObjectId(user_id)}))
    return render_template('all_notes.html', notes=notes_list)

@notes.route('/note', methods=['GET', 'POST'])
def create_note():
    user_id = session.get('user', {}).get('_id')
    if not user_id:
        return redirect(url_for('auth.login'))
    
    if request.method == 'POST':
        note_title = request.form.get('title', '')
        note_content = request.form.get('note', '')
        formatted_content = request.form.get('formatted_content', '')
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Add title and date to the formatted content
        header = f"<h2>{note_title}</h2><p>Date: {date}</p>"
        formatted_content = header + formatted_content
        
        note_id = str(uuid.uuid4())
        
        # Save the note for the specific user
        notes_collection.insert_one({
            "user_id": ObjectId(user_id),
            "note_id": note_id,
            "title": note_title,
            "content": note_content,
            "formatted_content": formatted_content,
            "created_at": datetime.now(),
            "expires_at": None
        })
        
        flash('Your note has been saved successfully!', 'info')
        return redirect(url_for('notes_app.all_notes'))

    return render_template('create.html')

@notes.route('/view/<note_id>', methods=['GET'])
def view_note(note_id):
    user_id = session.get('user', {}).get('_id')
    if not user_id:
        return redirect(url_for('auth.login'))
    
    # Fetch the note for the specific user
    note = notes_collection.find_one({"note_id": note_id, "user_id": ObjectId(user_id)})
    if note:
        return render_template(
            'view_note.html', 
            note_title=note["title"],
            note_content=note["content"].strip(),
            note_id=note_id,
            formatted_content=note["formatted_content"]
        )
    return "Note not found", 404



@notes.route('/download/<note_id>')
def download_note(note_id):
    user_id = session.get('user', {}).get('_id')
    if not user_id:
        return redirect(url_for('auth.login'))
    
    note = notes_collection.find_one({"note_id": note_id, "user_id": ObjectId(user_id)})
    if note:
        # Generate the content in memory instead of saving it to disk
        file_content = f"Title: {note['title']}\n"
        file_content += f"Date: {note['created_at'].strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        file_content += note["content"]
        
        # Use BytesIO to create a file-like object in memory
        file_stream = BytesIO(file_content.encode('utf-8'))
        
        # Set a filename for the download
        download_filename = f"{note['title']}.txt"
        
        return send_file(file_stream, as_attachment=True, download_name=download_filename)
    
    return "Note not found", 404


@notes.route('/edit/<note_id>', methods=['GET', 'POST'])
def edit_note(note_id):
    user_id = session.get('user', {}).get('_id')
    if not user_id:
        return redirect(url_for('auth.login'))
    
    note = notes_collection.find_one({"note_id": note_id, "user_id": ObjectId(user_id)})
    if request.method == 'POST' and note:
        note_title = request.form.get('title', '')
        note_content = request.form.get('note', '')
        formatted_content = request.form.get('formatted_content', '')
        
        notes_collection.update_one(
            {"note_id": note_id, "user_id": ObjectId(user_id)},
            {"$set": {
                "title": note_title,
                "content": note_content,
                "formatted_content": formatted_content,
                "updated_at": datetime.now()
            }}
        )
        
        flash('Your note has been updated successfully!', 'info')
        return redirect(url_for('notes_app.all_notes'))

    return render_template('edit_note.html', note=note)

@notes.route('/delete/<note_id>', methods=['POST'])
def delete_note(note_id):
    user_id = session.get('user', {}).get('_id')
    if not user_id:
        return redirect(url_for('auth.login'))
    
    notes_collection.delete_one({"note_id": note_id, "user_id": ObjectId(user_id)})
    flash('Note deleted successfully!', 'info')
    return redirect(url_for('notes_app.all_notes'))

@notes.route('/share/<note_id>', methods=['GET'])
def share_note_link(note_id):
    user_id = session.get('user', {}).get('_id')
    if not user_id:
        return redirect(url_for('auth.login'))
    
    note = notes_collection.find_one({"note_id": note_id, "user_id": ObjectId(user_id)})
    if note:
        share_token = secrets.token_urlsafe(16)
        expiration_time = datetime.now() + timedelta(hours=24)
        
        notes_collection.update_one(
            {"note_id": note_id},
            {"$set": {"share_token": share_token, "expires_at": expiration_time}}
        )
        
        share_link = url_for('notes_app.view_shared_note', note_id=note_id, token=share_token, _external=True)
        flash(f'Your share link is :  <a href="{share_link}" target="_blank">{share_link}</a>', 'info')
        return redirect(url_for('notes_app.all_notes'))
    return jsonify({"error": "Note not found"}), 404

@notes.route('/shared/<note_id>/<token>')
def view_shared_note(note_id, token):
    note = notes_collection.find_one({"note_id": note_id, "share_token": token})
    if note:
        if note.get("expires_at") and datetime.now() > note["expires_at"]:
            notes_collection.update_one({"note_id": note_id}, {"$unset": {"share_token": "", "expires_at": ""}})
            return "The link has expired.", 410
        return render_template(
            'share_view.html', 
            note_title=note["title"],
            note_content=note["content"].strip(),
            note_id=note_id,
            formatted_content=note["formatted_content"]
        )
    return "Invalid or expired link.", 404

src/routes/resume.py
from flask import Blueprint, redirect, url_for, session, render_template, request
from src.ATS.resume_score import parse_resume, calculate_ats_score
from src.database import get_user_by_id

ats_bp = Blueprint('ats', __name__)

@ats_bp.route('/resume_score', methods=['GET', 'POST'])
def index():
    # Fetch user data for profile picture display, whether GET or POST
    user = session.get('user')
    if user:
        user_id = user['_id']
        user_data = get_user_by_id(user_id)

        if user_data is None:
            return "User not found", 404

        display_data = {'profile_pic': user_data.get('profile_pic')}
    else:
        # Use default data if user is not in session
        display_data = {'profile_pic': 'default_profile_pic.jpg'}
    
    if request.method == 'POST':
        resume = request.files['resume']
        job_description = request.form['job_description']
        resume_text = parse_resume(resume)
        ats_score = calculate_ats_score(resume_text, job_description)
        
        return render_template('resume.html', score=ats_score, display_data=display_data)
    
    # For GET requests, no ATS score is initially shown
    return render_template('resume.html', score=None, display_data=display_data)

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Meta for Responsive Design -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Fav_Icon -->
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/Intelli_Logo.png') }}">
    <!-- CSS Import -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <!-- Loader CSS and JS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/loader.css') }}">
    <script src="{{ url_for('static', filename='js/loader.js') }}" defer></script>
    <!-- Fonts Import -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet">
    <title>IntelliHelper</title>
</head>

<body>
    <div id="loader" class="loader">
        <img src="{{ url_for('static', filename='images/Giffy-Loader.gif') }}" alt="Loading..." class="loader-gif">
    </div>

    <div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
    </div>
    <div class="navBar">
        <div class="logo">
            IntelliHelper
        </div>
        <div class="nav_links">
            <ul>
                <li><a href="{{ url_for('about.about') }}">About Us</a></li>
                
                <li>
                    <button onclick="toggleMenu()">Tabs</button>
                    <div class="dropdown-menu" style="display: none;">
                        <ul>
                            <li><a href="{{ url_for('medical.index') }}" title="Health Bot">Health Bot</a></li>
                            <li><a href="{{ url_for('ats.index') }}">Resume Checker</a></li>
                            <li><a href="{{ url_for('todo_app.index') }}">To-Do List</a></li>
                            <li><a href="{{ url_for('news.index') }}">News</a></li>
                            <li><a href="{{ url_for('text.index') }}">News Summary</a></li>
                            <li><a href="{{ url_for('notes_app.all_notes') }}">Notes</a></li>
                        </ul>
                    </div>
                    <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
                </li>
            </ul>
        </div>

        <div class="joining">
            {% if session.user %}
                <a href="{{ url_for('profile.profile') }}">
                    {% if display_data.profile_pic %}
                        <img src="data:image/png;base64,{{ display_data.profile_pic }}" alt="IH" class="profile-pic" />
                    {% else %}
                        <img src="{{ url_for('static', filename='images/dummy_profile_pic.png') }}" alt="IH" class="profile-pic" />
                    {% endif %}
                </a>
            {% else %}
                <div class="l_btn"><a href="{{ url_for('auth.login') }}">Login</a></div>
                <div class="s_btn"><a href="{{ url_for('auth.signup') }}">SignUp</a></div>
            {% endif %}
        </div>
        

    </div>

    <div class="separator"></div>

    <div class="jumbotron">
        <div class="j_data">
            JOIN..IMPROVE..<span id="j_data_highlight">LEARN.</span> 
            <div id="countdown" style="margin-top: 20px; font-size: 45px; font-weight: bold;">
                <br><br>
            </div>
            Welcome To IntelliHelper ! !<br>Get your Daily Solutions<br>Right Now
        </div>
    </div>



    </div>

    <div class="bottom_links">
        <ul>
            <li><a href="{{ url_for('ats.index') }}" title="Resume Checker" target="_blank">📄</a></li>
            <li><a href="{{ url_for('medical.index') }}" title="Health Bot" target="_blank">🩺</a></li>
            <li><a href="{{ url_for('todo_app.index') }}" title="To-Do List" target="_blank">📝</a></li>
            <li><a href="{{ url_for('news.index') }}" title="News" target="_blank">📰</a></li>
            <li><a href="{{ url_for('text.index') }}" title="News Summary" target="_blank">📋</a></li>
            <li><a href="{{ url_for('notes_app.all_notes') }}" title="Notes" target="_blank">&#128466</a></li>
        </ul>
    </div>


    <script>
        function toggleMenu() {
            const dropdownMenu = document.querySelector('.dropdown-menu');
            // Toggle display of the dropdown menu
            if (dropdownMenu.style.display === 'none' || dropdownMenu.style.display === '') {
                dropdownMenu.style.display = 'block';
            } else {
                dropdownMenu.style.display = 'none';
            }
        }

        document.addEventListener('click', function (event) {
            const dropdownMenu = document.querySelector('.dropdown-menu');
            const toggleButton = document.querySelector('button[onclick="toggleMenu()"]');

            // Check if the click is outside the dropdown and the button
            if (!dropdownMenu.contains(event.target) && !toggleButton.contains(event.target)) {
                dropdownMenu.style.display = 'none';
            }
        });

        function togglebot() {
            const botTab = document.querySelector('.health_bot_tab');
            botTab.classList.toggle('active');
        }

    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>

        $(document).ready(function() {
            $("#chatForm").on("submit", function(event) {
                event.preventDefault();

                const date = new Date();
                const time = `${date.getHours()}:${date.getMinutes().toString().padStart(2, '0')}`;
                const userInput = $("#text").val();

                const userMessage = `
                    <div class="msg-container user">
                        <div class="message">${userInput}</div>
                        <div class="msg-time">${time}</div>
                    </div>
                `;

                $("#messageArea").append(userMessage);
                $("#text").val("");

                $.ajax({
                    data: { msg: userInput },
                    type: "POST",
                    url: "/get",
                }).done(function(response) {
                    const botMessage = `
                        <div class="msg-container bot">
                            <div class="message">${response}</div>
                            <div class="msg-time">${time}</div>
                        </div>
                    `;
                    $("#messageArea").append(botMessage);
                    $("#messageArea").scrollTop($("#messageArea")[0].scrollHeight);
                });
            });
        });

        function updateCountdown() {
            const now = new Date();
            const newYear = new Date(now.getFullYear() + 1, 0, 1);
            const timeLeft = newYear - now;
    
            // Calculate days, hours, minutes, and seconds
            const days = Math.floor(timeLeft / (1000 * 60 * 60 * 24));
            const hours = Math.floor((timeLeft % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((timeLeft % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((timeLeft % (1000 * 60)) / 1000);
    
            // Update the countdown element
            document.getElementById("countdown").innerHTML =
                `Race against time and finish strong—complete your goals before the clock strikes the New Year!🎆⏳ <br> <span class="timer">${days}d ${hours}h ${minutes}m ${seconds}s</span>`;
        }
    
        // Update the countdown every second
        setInterval(updateCountdown, 1000);
        updateCountdown();
    </script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Meta for Responsive Design -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Fav_Icon -->
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/Intelli_Logo.png') }}">
    <!-- CSS Import -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <!-- Loader CSS and JS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/loader.css') }}">
    <script src="{{ url_for('static', filename='js/loader.js') }}" defer></script>
    <!-- Importing Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Abel&display=swap" rel="stylesheet">
    <title>Login - IntellHelper</title>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <script>
        alert("{{ message }}");
    </script>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div id="loader" class="loader">
        <img src="{{ url_for('static', filename='images/Giffy-Loader.gif') }}" alt="Loading..." class="loader-gif">
    </div>

    <div class="container">
        <div class="login-section">
            <h2>Login</h2>
            <form method="POST">
                {{ form.hidden_tag() }}
                <div class="input-group">
                    {{ form.username.label }}
                    {{ form.username(autocomplete="off", oninvalid="this.setCustomValidity('Please enter your name')",
                    oninput="setCustomValidity('')") }}
                </div>
                <div class="input-group password-container">
                    {{ form.password.label }}
                    {{ form.password() }}
                    <span class="eye-icon" id="eyeIcon" onclick="togglePassword()">
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                            fill="#337ab7">
                            <path
                                d="M480-320q75 0 127.5-52.5T660-500q0-75-52.5-127.5T480-680q-75 0-127.5 52.5T300-500q0 75 52.5 127.5T480-320Zm0-72q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm0 192q-146 0-266-81.5T40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200Zm0-300Zm0 220q113 0 207.5-59.5T832-500q-50-101-144.5-160.5T480-720q-113 0-207.5 59.5T128-500q50 101 144.5 160.5T480-280Z" />
                        </svg>
                    </span>
                </div>
                <div class="login-btn">
                    <input type="submit" value="Login">
                </div>
                <div class="forgot-password">
                    Forgot Password? <a href="{{ url_for('profile.forgot_password') }}"><span>Click Here</span></a>
                </div>
            </form>
        </div>

        <div class="signup-section">
            <h2>Not a Member yet? Join IntellHelper Today!</h2>
            <p>Ready to be part of something smarter? Click below and get started!</p>
            <a href="{{ url_for('auth.signup') }}" class="join-now-btn">Join Now</a>
        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const passwordInput = document.querySelector('input[name="password"]');
            const eyeIcon = document.getElementById('eyeIcon');

            passwordInput.addEventListener('focus', function () {
                eyeIcon.style.display = 'block';
            });

            passwordInput.addEventListener('blur', function () {
                if (passwordInput.value.length === 0) {
                    eyeIcon.style.display = 'none';
                }
            });

            passwordInput.addEventListener('input', function () {
                if (passwordInput.value.length > 0) {
                    eyeIcon.style.display = 'block';
                } else {
                    eyeIcon.style.display = 'none';
                }
            });
        });

        function togglePassword() {
            const passwordInput = document.querySelector('input[name="password"]');
            const eyeIcon = document.getElementById('eyeIcon');

            const eyeOpenSvg = `<svg xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 -960 960 960" width="24px" fill="#337ab7"><path d="m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-53 57Zm-31 23Zm0-248Zm0 75Z"/></svg>`;

            const eyeSvg = `<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#337ab7"><path d="M480-320q75 0 127.5-52.5T660-500q0-75-52.5-127.5T480-680q-75 0-127.5 52.5T300-500q0 75 52.5 127.5T480-320Zm0-72q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm0 192q-146 0-266-81.5T40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200Zm0-300Zm0 220q113 0 207.5-59.5T832-500q-50-101-144.5-160.5T480-720q-113 0-207.5 59.5T128-500q50 101 144.5 160.5T480-280Z"/></svg>`;

            if (passwordInput.type === "password") {
                passwordInput.type = "text";
                eyeIcon.innerHTML = eyeOpenSvg;
            } else {
                passwordInput.type = "password";
                eyeIcon.innerHTML = eyeSvg;
            }
        }

    </script>

</body>

</html>